In [14]:
# import essential libraries
import torch
import torch as th


In [15]:
# check pytorch version
import torch
print(torch.__version__)


2.9.1+cpu


In [16]:
# Scalar tensor
t_scalar = th.tensor(5)

In [18]:
# test tensor creation
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [17]:
# 1 D tensor

t_1D = th.tensor([1,2,3,4])

t_1D.shape

torch.Size([4])

In [19]:
# 2 D tensor

t_2D = th.tensor([[1, 2, 3, 4],
                  [1, 2, 3, 4],
                  [1, 2, 3, 4],
                 ])

t_2D.shape

torch.Size([3, 4])

In [20]:
# 3 D tensor

t_3D = th.tensor([
                 [[1, 2, 3, 4], [1, 2, 3, 4]],
                 [[1, 2, 3, 4], [1, 2, 3, 4]],
                 [[1, 2, 3, 4], [1, 2, 3, 4]]
                 ])

t_3D.shape

torch.Size([3, 2, 4])

In [21]:
# operations
# broadcasting works
t_2D + 10

tensor([[11, 12, 13, 14],
        [11, 12, 13, 14],
        [11, 12, 13, 14]])

In [23]:
# generate a tensor

gen_ten = th.rand(2,5,3)
gen_ten = gen_ten.to(device="cpu")
gen_ten

tensor([[[0.1359, 0.7716, 0.5377],
         [0.1189, 0.3862, 0.0469],
         [0.8920, 0.4121, 0.4300],
         [0.5114, 0.7829, 0.8530],
         [0.5540, 0.3223, 0.3089]],

        [[0.2638, 0.5151, 0.8339],
         [0.7055, 0.4374, 0.3902],
         [0.8527, 0.0520, 0.0665],
         [0.6403, 0.3768, 0.9921],
         [0.5202, 0.8717, 0.4206]]])

In [24]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)


In [25]:
tensor_B.shape

torch.Size([3, 2])

In [26]:
# 7   8     9
# 10  11   12

x = tensor_B.T
x

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [28]:
print(tensor_A.shape)
print(tensor_B.shape)

torch.Size([3, 2])
torch.Size([3, 2])


In [29]:
tensor_A = th.rand(3,2)
tensor_B = th.rand(2,3)

tensor_A @ tensor_B  # matrix multiplication

tensor([[0.6933, 0.6231, 0.3371],
        [0.2416, 0.5054, 0.2941],
        [0.3570, 0.2817, 0.1496]])

In [31]:
print(tensor_A.shape)
print(tensor_B.shape)
print(tensor_B.T.shape) # transpose

torch.Size([3, 2])
torch.Size([2, 3])
torch.Size([3, 2])


In [ ]:
output = torch.matmul(tensor_A, tensor_B.T)
output


In [33]:
x

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [35]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features  =2, # in_features = matches inner dimension of input 
                         out_features =6) # out_features = describes outer value 

linear

Linear(in_features=2, out_features=6, bias=True)

In [36]:
x = tensor_A

In [37]:
output = linear(x)
output

tensor([[ 1.1313,  0.6284,  0.4361,  0.1966,  0.2105,  0.3329],
        [ 0.9745,  0.0945,  0.2628, -0.2572,  0.8685,  0.5300],
        [ 0.8033,  0.3955,  0.4051,  0.0883,  0.3129,  0.1751]],
       grad_fn=<AddmmBackward0>)

In [38]:
# print input and output shapes
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 1.1313,  0.6284,  0.4361,  0.1966,  0.2105,  0.3329],
        [ 0.9745,  0.0945,  0.2628, -0.2572,  0.8685,  0.5300],
        [ 0.8033,  0.3955,  0.4051,  0.0883,  0.3129,  0.1751]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])
